config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root 'splash#index'
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  unauthenticated do
    root "splash#index"
  end
  resources :groups do
    resources :expenses
  end
  # resources :group_expenses
  # resources :expenses
  # resources :groups
  # resources :users

end

app/models/group.rb
class Group < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User'
  has_many :group_expense
  has_many :expenses, through: :group_expense

  # Attributes and Validations
  validates :name, presence: true
  validates :icon, presence: true

  def self.display_groups
    order(created_at: :desc)
  end

  def total_value
    expenses.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = current_user.groups.display_groups
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.author = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="border-end border-start me-1 ms-1 pt-3" style="height: 100vh;">
  <%= form_with(model: group) do |form| %>
    <% if group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class ="d-grid mb-1 pe-1 ps-1" >
      <%= form.text_field :name , placeholder: "Category name" %>
    </div>

    <div class ="d-grid mb-1 pe-1 ps-1" >
      <%= form.url_field :icon, placeholder: "Category icon" %>
    </div>

    <div class ="d-grid mb-1 pe-1 ps-1" >
      <%= form.submit class:'btn btn-primary'%>
    </div>
  <% end %>
<div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div> 
  <nav class="navbar navbar-light bg-primary justify-content-between text-light">
    <button class="btn btn-primary" > <i class="fa-solid fa-bars"></i></button>
    <h2> GROUP</h2>
    <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-primary me-2" do %>
      <i class="fa fa-user"></i> Logout
    <% end %>
  </nav>
  <div id="groups" class ="border-end border-start me-1 ms-1 pt-0" style="height: 90vh;">
    <p style="color: green"><%= notice %></p>  
    <% @groups.each do |group| %>
      <div class="card m-2">
      <%= link_to group_expenses_path(group), class: 'cont' do %>
        <div class="row">
          <div class="col-4 text-center"> 
            <img src="<%= group.icon%>"alt="picture alt" class="img-thumbnail image ps-1">
          </div>
          <div class="col-4 text-center"> 
            <h3><%= group.name %></h3>
          </div>
          <div class="col-4 text-center"> 
            <p class="pe-1">Total amount:  $<%= group.total_value %></p>
          </div>
        </div>
        <% end %>
      </div>
    <% end %>
  
    <div class="fixed-bottom d-flex justify-content-center align-items-center" style="background: #60B524;height:50px; ">

      <%= link_to "New group", new_group_path, class:"btn text-light fs-6", style:"border:1px solid white; width:95%;" %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div> 
  <nav class="navbar navbar-light bg-primary justify-content-between text-light">
    <%= link_to( raw("<i class='fas fa-arrow-left'></i>"),groups_path, class:'btn btn-primary ' )%>

    <h2>New CATEGORY</h2>
    <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-primary me-2" do %>
      <i class="fa fa-user"></i> Logout
    <% end %>
  </nav>
   <%= render "form", group: @group %>
</div>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>