config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root 'splash#index'
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  unauthenticated do
    root "splash#index"
  end
  resources :groups do
    resources :expenses
  end
  # resources :group_expenses
  # resources :expenses
  # resources :groups
  # resources :users

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group
  # GET /expenses or /expenses.json
  def index
    @expenses = Group.find(@group.id).expenses.order(created_at: :desc)
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user
    Rails.logger.info @expense.inspect

    respond_to do |format|
      if @expense.save
        @group1 = Group.find(params[:expense][:group_id])
        @group1.expenses << @expense

        format.html { redirect_to group_expenses_path(@group), notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, :author_id)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div class="card" style=" width:90%; margin:0 auto">
  <div class="row">
    <div class="col-6 text-center"> Name:<%= expense.name %> </div>
    <div class="col-6 text-center"> Amount:<%= expense.amount %> </div>
  </div>
  <div class="text-center">
    Create at:<%= "#{expense.created_at.day} #{expense.created_at.strftime("%b")} #{expense.created_at.year}"%>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<div> 
  <nav class="navbar navbar-light bg-primary justify-content-between text-light">
    <%= link_to( raw("<i class='fas fa-arrow-left'></i>"),groups_path, class:'btn btn-primary ' )%>
      
    <h2>TRANSACTIONS</h2>
    <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-primary me-2" do %>
      <i class="fa fa-user"></i> Logout
    <% end %>
  </nav>

  <div class="border-end border-start me-1 ms-1 pt-3" style="height: 80vh;">
    <div class="row">
    <div class="col-4 text-center"> 
      <img src="<%= @group.icon%>"alt="picture alt" class="img-thumbnail image ps-1">
    </div>
    <div class="col-4 text-center"> 
      <h3><%= @group.name %></h3>
    </div>
    <div class="col-4 text-center"> 
      <p class="pe-1">Total amount:  $<%= @group.total_value %></p>
    </div>
  </div>

    <p style="color: green"><%= notice %></p>
    <% @expenses.each do |expense| %>
        <%= render expense %>
    <% end %>
    <div class="fixed-bottom d-flex justify-content-center align-items-center" style="background: #60B524;height:50px; ">

       <%= link_to "New expense", new_group_expense_path(@group), class:"btn text-light fs-6", style:"border:1px solid white; width:95%;" %>
      </div>
</div>

app/views/expenses/new.html.erb
<div> 
  <nav class="navbar navbar-light bg-primary justify-content-between text-light">
    <%= link_to( raw("<i class='fas fa-arrow-left'></i>"),group_expenses_path, class:'btn btn-primary ' )%>
      
    <h2>NEW TRANSACTION</h2>
    <%= button_to destroy_user_session_path, method: :delete, class: "btn btn-primary me-2" do %>
      <i class="fa fa-user"></i> Logout
    <% end %>
  </nav>
  <div class="border-end border-start me-1 ms-1 pt-3" style="height: 100vh;">
    <%= form_with model: [@group, @expense], class:"add-form" do |form| %>
        <div class="d-grid mb-1 pe-1 ps-1">
          <%= form.text_field :name, class: "i-control", placeholder: 'Name' %>
          <% if @expense.errors.has_key?(:name) %>
            <p class="error-message"><%= @expense.errors[:name].first %></p>
          <% end %>
        </div>
  
      <div class="d-grid mb-1 pe-1 ps-1">
        <%= form.number_field :amount, class: "i-control", placeholder: 'Amount' %>
        <% if @expense.errors.has_key?(:amount) %>
          <p class="error-message"><%= @expense.errors[:amount].first %></p>
        <% end %>
      </div>
  
      <div class="d-grid mb-1 pe-1 ps-1">
        <%= form.collection_select :group_id, current_user.groups, :id, :name, {}, class: "form-select i-control" %>
        <% if @expense.errors.has_key?(:group_id) %>
          <p class="error-message"><%= @expense.errors[:group_id].first %></p>
        <% end %>
      </div>
    
  
      <div class="d-grid mb-1 pe-1 ps-1">
        <%= form.submit "Save" ,class: "btn btn-light border" %>
      </div>
    <% end %>
  </div>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>